message (STATUS "Checking for nanomsg...")

if(NOT DEFINED NANOMSG_ROOT)
	set(NANOMSG_ROOT /usr /usr/local $ENV{NANOMSG_ROOT})
endif(NOT DEFINED NANOMSG_ROOT)

find_path(NANOMSG_INCLUDE_DIRS
  nanomsg/nn.h
  PATHS ${NANOMSG_ROOT}
  PATH_SUFFIXES nanomsg/include include
)

if(WIN32)
	set(CMAKE_FIND_LIBRARY_SUFFIXES .lib .a ${CMAKE_FIND_LIBRARY_SUFFIXES})
else()
	set(CMAKE_FIND_LIBRARY_SUFFIXES .a .dylib)
endif()

find_library(NANOMSG_LIBRARIES
	NAMES nanomsg
	PATHS ${NANOMSG_ROOT}
	PATH_SUFFIXES lib
)

find_library(NANOMSG_LIBRARIES
	NAMES nanomsg
	PATHS ${NANOMSG_ROOT}
	PATH_SUFFIXES lib
)

if (NANOMSG_LIBRARIES_NOTFOUND AND NOT NANOMSG_USE_STATIC_LIBS)
	set(CMAKE_FIND_LIBRARY_SUFFIXES ${_snappy_ORIG_CMAKE_FIND_LIBRARY_SUFFIXES})
	find_library(NANOMSG_LIBRARIES
		NAMES nanomsg
		PATHS ${NANOMSG_ROOT}
		PATH_SUFFIXES lib
	)
endif()

mark_as_advanced(NANOMSG_INCLUDE_DIR NANOMSG_LIBRARIES)


include("${CMAKE_ROOT}/Modules/FindPackageHandleStandardArgs.cmake")
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Nanomsg DEFAULT_MSG NANOMSG_INCLUDE_DIRS NANOMSG_LIBRARIES)
